# Generated by Django 5.1.2 on 2024-10-17 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopmanager", "0002_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
