# Generated by Django 5.1.2 on 2024-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_cakebase_cake_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="cakes/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
