# Generated by Django 5.1.2 on 2024-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_cake_base_remove_cake_filling_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_name", models.CharField(max_length=100)),
                (
                    "additional_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cake",
            name="image",
        ),
        migrations.RemoveField(
            model_name="filling",
            name="cake",
        ),
        migrations.RemoveField(
            model_name="filling",
            name="extra_price",
        ),
        migrations.RemoveField(
            model_name="size",
            name="cake",
        ),
        migrations.RemoveField(
            model_name="size",
            name="size",
        ),
        migrations.AddField(
            model_name="cake",
            name="fillings",
            field=models.ManyToManyField(related_name="cakes", to="product.filling"),
        ),
        migrations.AddField(
            model_name="cake",
            name="sizes",
            field=models.ManyToManyField(related_name="cakes", to="product.size"),
        ),
        migrations.AddField(
            model_name="filling",
            name="additional_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="size",
            name="size_name",
            field=models.CharField(default="default size", max_length=50),
        ),
        migrations.AlterField(
            model_name="cake",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="filling",
            name="filling_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="size",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name="cake",
            name="bases",
            field=models.ManyToManyField(related_name="cakes", to="product.base"),
        ),
        migrations.DeleteModel(
            name="CakeBase",
        ),
    ]
