# Generated by Django 5.1.2 on 2024-10-28 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_cake_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Size",
            new_name="Sizes",
        ),
    ]
